# -*- coding: utf-8 -*-
"""Task_1(Chatbot).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19UC9P4QACAvoGJixEVkDSkhPM6m7GexM
"""

print ("Chatbot: Hello, I am a Chatbot...")
print("Chatbot: How may I help you...")

usr_inp = input(str("User: "))

predefined_set = {
"Who's the Prime minister of India":"Mr.Narenndra Modi is the Prime minister of India",
"What skills are required for IT job":"Good Programming, COmmunication skills etc.",
"What are you":"I am a chatbot... and i am here to help",
"Independence day date ?":"Independence day of India is celebrated on 15 August.",
"Can you sing":"No I can't."
}

if usr_inp in predefined_set :
  print("Chatbot : ", predefined_set[usr_inp])

else:
   print("I am sorry I cant answer that. ")

