# -*- coding: utf-8 -*-
"""Task_2(Tic Tac Toe).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ruDaX9kg4i9All-8qVqH5RQ_aLN8L5lT
"""

import random
board = ['-','-','-',
         '-','-','-',
         '-','-','-']
player1 = "X"
winner = None
continued= True

def gameboard(board):
  print(board[0] + "|" + board[1] + "|" + board[2] )
  print("-----")
  print(board[3] + "|" + board[4] + "|" + board[5] )
  print("-----")
  print(board[6] + "|" + board[7] + "|" + board[8] )

def usrinp(board):
  x = int(input("Enter the position number to mark."))
  if board[x-1] == "-":
      board[x-1] = player1
  else:
    print("The spot is already marked, choose another one.")

def Vertical(board):
  global winner
  if board[0] == board[3] == board[6] and board[0] != "-":
    winner = board[0]
    return True
  if board[1] == board[4] == board[7] and board[1] != "-":
    winner = board[1]
    return True
  if board[2] == board[5] == board[8] and board[2] != "-":
    winner = board[2]
    return True

def Horizontal(board):
  global winner
  if board[0] == board[1] == board[2] and board[0] != "-":
    winner = board[0]
    return True
  if board[3] == board[4] == board[5] and board[3] != "-":
    winner = board[3]
    return True
  if board[6] == board[7] == board[8] and board[6] != "-":
    winner = board[6]
    return True

def Diagonal(board):
  global winner
  if board[0] == board[4] == board[8] and board[0] != "-":
    winner = board[0]
    return True
  if board[2] == board[4] == board[6] and board[2] != "-":
    winner = board[2]
    return True

def Win(board):
  global continued
  if Vertical(board):
    gameboard(board)
    print("The winner is: ",winner)
    continued = False
  elif Horizontal(board):
    gameboard(board)
    print("The winner is: ",winner)
    continued = False
  elif Diagonal(board):
    gameboard(board)
    print("The winner is: ",winner)
    continued = False

def Tied(board):
  global continued
  if "-" not in board:
    gameboard(board)
    print("It is a tie.")
    continued = False

def Player2():
  global player1
  if player1 == "X":
    player1 = "O"
  else:
    player1 = "X"

def Randomchoice(board):
  while player1 == "O":
    position = random.randint(0,8)
    if board[position] == "-":
      board[position] = "O"
      Player2()

while continued:
  gameboard(board)
  usrinp(board)
  Win(board)
  Tied(board)
  Player2()
  Randomchoice(board)
  Win(board)
  Tied(board)

